site_name: pyformatting
nav:
    - Home: index.md
    - Docs:
      - Getting started: getting-started.md
      - Optional formatting: optional.md
      - Default formatting: default.md
      - Base Formatter: base.md
theme: readthedocs
